# Generated by Django 6.0.7 on 2026-08-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('Steelworks', 'Stalownia'), ('Refinery', 'Rafineria'), ('Power Plant', 'Elektrownia')], max_length=32)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('ae_focus', models.CharField(blank=True, max_length=300)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True, default='Obiekt przykładowy - scenariusz demo; brak publicznego potwierdzenia kontraktu AE Steel.')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Zakład',
                'verbose_name_plural': 'Zakłady',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DemoEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_id', models.CharField(max_length=64)),
                ('n_cylinders', models.PositiveSmallIntegerField()),
                ('scenario', models.CharField(choices=[('clean', 'Sprawny'), ('zakoksowany', 'Zakoksowany'), ('multi', 'Wiele usterek')], max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_engines', to='api.factory')),
            ],
            options={
                'verbose_name': 'Silnik demo',
                'verbose_name_plural': 'Silniki demo',
                'ordering': ['sort_order', 'engine_id'],
                'unique_together': {('factory', 'engine_id')},
            },
        ),
    ]
