# Generated by Django 6.0.7 on 2026-08-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_demoengine_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='custom_detail_url',
            field=models.CharField(blank=True, help_text='Puste = domyślne /api/factories/{slug}/. Na prezentację: pełny URL lub ścieżka.', max_length=500, verbose_name='Własny URL szczegółów'),
        ),
        migrations.AddField(
            model_name='factory',
            name='custom_predict_url',
            field=models.CharField(blank=True, help_text='Puste = domyślne /api/predict/.', max_length=500, verbose_name='Własny URL predict'),
        ),
        migrations.AddField(
            model_name='factory',
            name='custom_telemetry_url',
            field=models.CharField(blank=True, help_text='Puste = domyślne /api/factories/{slug}/telemetry/. Frontend używa tego linku.', max_length=500, verbose_name='Własny URL telemetrii'),
        ),
    ]
