# Generated by Django 6.0.7 on 2026-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_factory_custom_api_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='facility_type',
            field=models.CharField(blank=True, choices=[('Steelworks', 'Stalownia'), ('Refinery', 'Rafineria'), ('Power Plant', 'Elektrownia'), ('Ship', 'Statek')], default='Steelworks', max_length=32),
        ),
        migrations.AlterField(
            model_name='factory',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
