# Generated by Django 6.0.7 on 2026-08-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_simplify_factory_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='custom_detail_url',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='custom_predict_url',
        ),
        migrations.RemoveField(
            model_name='factory',
            name='custom_telemetry_url',
        ),
    ]
