# Generated by Django 6.0.7 on 2026-08-25 08:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_custom_api_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='csv_file',
            field=models.FileField(blank=True, help_text='CSV z widmami: engine_id, cylinder, n_cylinders, mV_0…mV_20. Puste = losowanie z train.csv.', upload_to=api.models.factory_csv_upload_to),
        ),
    ]
